#!/bin/bash
set -e

# Setup Pseudopotentials Script
# Downloads SSSP Efficiency/Precision pseudopotentials for Quantum ESPRESSO.

PSEUDO_DIR="./pseudos"
SSSP_URL="https://archive.materialscloud.org/record/file?filename=SSSP_1.3.0_PBE_efficiency.tar.gz&record_id=1466"
# For Precision, use: https://archive.materialscloud.org/record/file?filename=SSSP_1.3.0_PBE_precision.tar.gz&record_id=1466

echo "Setting up Pseudopotentials..."

if [ -d "$PSEUDO_DIR" ]; then
    echo "Directory $PSEUDO_DIR already exists. Skipping download."
    exit 0
fi

mkdir -p "$PSEUDO_DIR"
cd "$PSEUDO_DIR"

echo "Downloading SSSP Efficiency (v1.3.0)..."
curl -L -o sssp.tar.gz "$SSSP_URL"

echo "Extracting..."
tar -xzvf sssp.tar.gz
rm sssp.tar.gz

# The archive might extract to a subdirectory or current.
# SSSP typically extracts directly or into a folder.
# Materials Cloud archives usually contain the files directly or in a folder named after the version.

echo "Pseudopotentials setup in $PSEUDO_DIR"

# Note: Users need to ensure config_meta.yaml points to this directory.
# The default config_meta.yaml generated by setup_experiment.py already points to ./pseudos
